export const megaJackpotAbi = [
  {
    type: "function",
    name: "deposit",
    stateMutability: "payable",
    inputs: [{ name: "referrer", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
  { type: "function", name: "claimPrize", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "claimReferralReward", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "triggerDraw", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "retryDraw", stateMutability: "nonpayable", inputs: [], outputs: [] },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  { type: "function", name: "totalPool", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "phase", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
  {
    type: "function",
    name: "countdownDeadline",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "countdownHardDeadline",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "windowDeposits",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "poolUsdValue",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "usd", type: "uint256" },
      { name: "ethUsdPrice", type: "int256" },
    ],
  },
  {
    type: "function",
    name: "winChancePpm",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "accountInfo",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [
      { name: "balance", type: "uint256" },
      { name: "withdrawUnlockAt", type: "uint256" },
      { name: "referrer", type: "address" },
      { name: "referredVolume", type: "uint256" },
      { name: "referralReward", type: "uint256" },
      { name: "referredUsers", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "referralRewardClaimed",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "participantCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  { type: "function", name: "winner", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "prizeAmount", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "prizeClaimed", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  {
    type: "event",
    name: "Deposited",
    inputs: [
      { name: "account", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "referrer", type: "address", indexed: true },
      { name: "newBalance", type: "uint256", indexed: false },
      { name: "newTotalPool", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Withdrawn",
    inputs: [
      { name: "account", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "newBalance", type: "uint256", indexed: false },
      { name: "newTotalPool", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ReferrerSet",
    inputs: [
      { name: "account", type: "address", indexed: true },
      { name: "referrer", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "ReferralRewardClaimed",
    inputs: [
      { name: "referrer", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CountdownStarted",
    inputs: [
      { name: "deadline", type: "uint256", indexed: false },
      { name: "hardDeadline", type: "uint256", indexed: false },
      { name: "totalPool", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CountdownExtended",
    inputs: [
      { name: "newDeadline", type: "uint256", indexed: false },
      { name: "windowDepositTotal", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "WinnerSelected",
    inputs: [
      { name: "winner", type: "address", indexed: true },
      { name: "prize", type: "uint256", indexed: false },
      { name: "fee", type: "uint256", indexed: false },
      { name: "randomWord", type: "uint256", indexed: false },
    ],
  },
] as const;
